db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/spring_crud_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.username=root
db.password=root123

hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.connection.characterEncoding=UTF-8
hibernate.connection.useUnicode=true
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update
jdbc.url=jdbc:mysql://localhost:3306/spring_crud_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC